/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'land' : IDL.Null,
  'plot' : IDL.Null,
});
export const PropertyId = IDL.Nat;
export const ListingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'sold' : IDL.Null,
  'available' : IDL.Null,
});
export const Time = IDL.Int;
export const PropertyListing = IDL.Record({
  'id' : PropertyId,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'createdAt' : Time,
  'size' : IDL.Float64,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'price' : IDL.Float64,
  'location' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const InquiryId = IDL.Nat;
export const Inquiry = IDL.Record({
  'id' : InquiryId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'propertyId' : PropertyId,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'contacted' : IDL.Bool,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        PropertyType,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [PropertyId],
      [],
    ),
  'deleteListing' : IDL.Func([PropertyId], [], []),
  'filterListingsByMaxPrice' : IDL.Func(
      [IDL.Float64],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'filterListingsByType' : IDL.Func(
      [PropertyType],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'filterListingsByTypeAndPrice' : IDL.Func(
      [PropertyType, IDL.Float64],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getAvailableListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInquiriesByContactStatus' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getInquiriesByProperty' : IDL.Func(
      [PropertyId],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getListing' : IDL.Func([PropertyId], [PropertyListing], ['query']),
  'getPropertyInquiryCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(PropertyId, IDL.Nat))],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markInquiryContacted' : IDL.Func([InquiryId], [], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, PropertyId],
      [InquiryId],
      [],
    ),
  'updateListing' : IDL.Func(
      [
        PropertyId,
        IDL.Text,
        IDL.Text,
        PropertyType,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        ListingStatus,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'land' : IDL.Null,
    'plot' : IDL.Null,
  });
  const PropertyId = IDL.Nat;
  const ListingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'sold' : IDL.Null,
    'available' : IDL.Null,
  });
  const Time = IDL.Int;
  const PropertyListing = IDL.Record({
    'id' : PropertyId,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'createdAt' : Time,
    'size' : IDL.Float64,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'price' : IDL.Float64,
    'location' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const InquiryId = IDL.Nat;
  const Inquiry = IDL.Record({
    'id' : InquiryId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'propertyId' : PropertyId,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'contacted' : IDL.Bool,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          PropertyType,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [PropertyId],
        [],
      ),
    'deleteListing' : IDL.Func([PropertyId], [], []),
    'filterListingsByMaxPrice' : IDL.Func(
        [IDL.Float64],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'filterListingsByType' : IDL.Func(
        [PropertyType],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'filterListingsByTypeAndPrice' : IDL.Func(
        [PropertyType, IDL.Float64],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
    'getAvailableListings' : IDL.Func(
        [],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInquiriesByContactStatus' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getInquiriesByProperty' : IDL.Func(
        [PropertyId],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getListing' : IDL.Func([PropertyId], [PropertyListing], ['query']),
    'getPropertyInquiryCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(PropertyId, IDL.Nat))],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markInquiryContacted' : IDL.Func([InquiryId], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, PropertyId],
        [InquiryId],
        [],
      ),
    'updateListing' : IDL.Func(
        [
          PropertyId,
          IDL.Text,
          IDL.Text,
          PropertyType,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          ListingStatus,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };