/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'id' : InquiryId,
  'name' : string,
  'createdAt' : Time,
  'propertyId' : PropertyId,
  'email' : string,
  'message' : string,
  'contacted' : boolean,
  'phone' : string,
}
export type InquiryId = bigint;
export type ListingStatus = { 'pending' : null } |
  { 'sold' : null } |
  { 'available' : null };
export type PropertyId = bigint;
export interface PropertyListing {
  'id' : PropertyId,
  'status' : ListingStatus,
  'title' : string,
  'propertyType' : PropertyType,
  'createdAt' : Time,
  'size' : number,
  'description' : string,
  'updatedAt' : Time,
  'price' : number,
  'location' : string,
  'images' : Array<string>,
}
export type PropertyType = { 'commercial' : null } |
  { 'land' : null } |
  { 'plot' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [string, string, PropertyType, number, number, string, Array<string>],
    PropertyId
  >,
  'deleteListing' : ActorMethod<[PropertyId], undefined>,
  'filterListingsByMaxPrice' : ActorMethod<[number], Array<PropertyListing>>,
  'filterListingsByType' : ActorMethod<[PropertyType], Array<PropertyListing>>,
  'filterListingsByTypeAndPrice' : ActorMethod<
    [PropertyType, number],
    Array<PropertyListing>
  >,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllListings' : ActorMethod<[], Array<PropertyListing>>,
  'getAvailableListings' : ActorMethod<[], Array<PropertyListing>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInquiriesByContactStatus' : ActorMethod<[boolean], Array<Inquiry>>,
  'getInquiriesByProperty' : ActorMethod<[PropertyId], Array<Inquiry>>,
  'getListing' : ActorMethod<[PropertyId], PropertyListing>,
  'getPropertyInquiryCounts' : ActorMethod<[], Array<[PropertyId, bigint]>>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markInquiryContacted' : ActorMethod<[InquiryId], undefined>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, PropertyId],
    InquiryId
  >,
  'updateListing' : ActorMethod<
    [
      PropertyId,
      string,
      string,
      PropertyType,
      number,
      number,
      string,
      ListingStatus,
      Array<string>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];