/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type InquiryId = bigint;
export type Time = bigint;
export type PropertyId = bigint;
export interface PropertyListing {
    id: PropertyId;
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    createdAt: Time;
    size: number;
    description: string;
    updatedAt: Time;
    price: number;
    location: string;
    images: Array<string>;
}
export interface Inquiry {
    id: InquiryId;
    name: string;
    createdAt: Time;
    propertyId: PropertyId;
    email: string;
    message: string;
    contacted: boolean;
    phone: string;
}
export enum ListingStatus {
    pending = "pending",
    sold = "sold",
    available = "available"
}
export enum PropertyType {
    commercial = "commercial",
    land = "land",
    plot = "plot"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createListing(title: string, description: string, propertyType: PropertyType, price: number, size: number, location: string, images: Array<string>): Promise<PropertyId>;
    deleteListing(id: PropertyId): Promise<void>;
    filterListingsByMaxPrice(maxPrice: number): Promise<Array<PropertyListing>>;
    filterListingsByType(propertyType: PropertyType): Promise<Array<PropertyListing>>;
    filterListingsByTypeAndPrice(propertyType: PropertyType, maxPrice: number): Promise<Array<PropertyListing>>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllListings(): Promise<Array<PropertyListing>>;
    getAvailableListings(): Promise<Array<PropertyListing>>;
    getCallerUserRole(): Promise<UserRole>;
    getInquiriesByContactStatus(contacted: boolean): Promise<Array<Inquiry>>;
    getInquiriesByProperty(propertyId: PropertyId): Promise<Array<Inquiry>>;
    getListing(id: PropertyId): Promise<PropertyListing>;
    getPropertyInquiryCounts(): Promise<Array<[PropertyId, bigint]>>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    loginAsAdminWithPassword(password: string): Promise<boolean>;
    markInquiryContacted(id: InquiryId): Promise<void>;
    submitInquiry(name: string, email: string, phone: string, message: string, propertyId: PropertyId): Promise<InquiryId>;
    updateListing(id: PropertyId, title: string, description: string, propertyType: PropertyType, price: number, size: number, location: string, status: ListingStatus, images: Array<string>): Promise<void>;
}
import type { ListingStatus as _ListingStatus, PropertyId as _PropertyId, PropertyListing as _PropertyListing, PropertyType as _PropertyType, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createListing(arg0: string, arg1: string, arg2: PropertyType, arg3: number, arg4: number, arg5: string, arg6: Array<string>): Promise<PropertyId> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteListing(arg0: PropertyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async filterListingsByMaxPrice(arg0: number): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterListingsByMaxPrice(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterListingsByMaxPrice(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterListingsByType(arg0: PropertyType): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterListingsByType(to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterListingsByType(to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterListingsByTypeAndPrice(arg0: PropertyType, arg1: number): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterListingsByTypeAndPrice(to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterListingsByTypeAndPrice(to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return result;
        }
    }
    async getAllListings(): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableListings(): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableListings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableListings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiriesByContactStatus(arg0: boolean): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiriesByContactStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiriesByContactStatus(arg0);
            return result;
        }
    }
    async getInquiriesByProperty(arg0: PropertyId): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiriesByProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiriesByProperty(arg0);
            return result;
        }
    }
    async getListing(arg0: PropertyId): Promise<PropertyListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_PropertyListing_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_PropertyListing_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertyInquiryCounts(): Promise<Array<[PropertyId, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyInquiryCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyInquiryCounts();
            return result;
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markInquiryContacted(arg0: InquiryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markInquiryContacted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markInquiryContacted(arg0);
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: PropertyId): Promise<InquiryId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async loginAsAdminWithPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.loginAsAdminWithPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginAsAdminWithPassword(arg0);
            return result;
        }
    }
    async updateListing(arg0: PropertyId, arg1: string, arg2: string, arg3: PropertyType, arg4: number, arg5: number, arg6: string, arg7: ListingStatus, arg8: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, arg1, arg2, to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, to_candid_ListingStatus_n14(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, arg1, arg2, to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, to_candid_ListingStatus_n14(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
}
function from_candid_ListingStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyListing_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyListing): PropertyListing {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PropertyId;
    status: _ListingStatus;
    title: string;
    propertyType: _PropertyType;
    createdAt: _Time;
    size: number;
    description: string;
    updatedAt: _Time;
    price: number;
    location: string;
    images: Array<string>;
}): {
    id: PropertyId;
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    createdAt: Time;
    size: number;
    description: string;
    updatedAt: Time;
    price: number;
    location: string;
    images: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_ListingStatus_n8(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: from_candid_PropertyType_n10(_uploadFile, _downloadFile, value.propertyType),
        createdAt: value.createdAt,
        size: value.size,
        description: value.description,
        updatedAt: value.updatedAt,
        price: value.price,
        location: value.location,
        images: value.images
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial: null;
} | {
    land: null;
} | {
    plot: null;
}): PropertyType {
    return "commercial" in value ? PropertyType.commercial : "land" in value ? PropertyType.land : "plot" in value ? PropertyType.plot : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    sold: null;
} | {
    available: null;
}): ListingStatus {
    return "pending" in value ? ListingStatus.pending : "sold" in value ? ListingStatus.sold : "available" in value ? ListingStatus.available : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertyListing>): Array<PropertyListing> {
    return value.map((x)=>from_candid_PropertyListing_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ListingStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): _ListingStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): {
    pending: null;
} | {
    sold: null;
} | {
    available: null;
} {
    return value == ListingStatus.pending ? {
        pending: null
    } : value == ListingStatus.sold ? {
        sold: null
    } : value == ListingStatus.available ? {
        available: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    commercial: null;
} | {
    land: null;
} | {
    plot: null;
} {
    return value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.land ? {
        land: null
    } : value == PropertyType.plot ? {
        plot: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
